-- Pinned treesitter parser revisions. Source of truth for `make warm`.
-- Regenerated by `make update`. Edit by hand only when intentionally pinning.
-- Values are whatever ref `nvim-treesitter`'s install_info uses — usually a
-- commit SHA, occasionally a tag (e.g. python's `v0.25.0`).
--
-- A hand edit here only takes effect via `make update`/`make warm` (which
-- reinstalls): just restarting nvim does NOT re-pin an already-installed
-- parser. See lua/config/ts_pinned.lua for why.
--
-- Keep the body below bare `name = "rev"` lines: update-pins.sh regenerates it
-- and drops any in-body comments, so rationale that needs to survive lives up
-- here. `terraform` and `hcl` currently pin the same SHA — terraform is the
-- dialects/terraform grammar in the tree-sitter-hcl family. nvim-treesitter
-- sources them from two kept-in-sync repos (tree-sitter-grammars/ and
-- MichaHoffmann/), and `make update` re-derives each pin independently, so a
-- future divergence just yields two SHAs rather than breaking anything.
return {
  markdown = "f969cd3ae3f9fbd4e43205431d0ae286014c05b5",
  markdown_inline = "f969cd3ae3f9fbd4e43205431d0ae286014c05b5",
  typescript = "75b3874edb2dc714fb1fd77a32013d0f8699989f",
  tsx = "75b3874edb2dc714fb1fd77a32013d0f8699989f",
  javascript = "58404d8cf191d69f2674a8fd507bd5776f46cb11",
  jsdoc = "658d18dcdddb75c760363faa4963427a7c6b52db",
  python = "v0.25.0",
  go = "2346a3ab1bb3857b48b29d779a1ef9799a248cd7",
  gomod = "2e886870578eeba1927a2dc4bd2e2b3f598c5f9a",
  gosum = "27816eb6b7315746ae9fcf711e4e1396dc1cf237",
  gowork = "949a8a470559543857a62102c84700d291fc984c",
  gotmpl = "aa71f63de226c5592dfbfc1f29949522d7c95fac",
  rust = "77a3747266f4d621d0757825e6b11edcbf991ca5",
  c = "ae19b676b13bdcc13b7665397e6d9b14975473dd",
  cpp = "8b5b49eb196bec7040441bee33b2c9a4838d6967",
  lua = "10fe0054734eec83049514ea2e718b2a56acd0c9",
  luadoc = "873612aadd3f684dd4e631bdf42ea8990c57634e",
  vim = "3092fcd99eb87bbd0fc434aa03650ba58bd5b43b",
  vimdoc = "f061895a0eff1d5b90e4fb60d21d87be3267031a",
  query = "fc5409c6820dd5e02b0b0a309d3da2bfcde2db17",
  bash = "a06c2e4415e9bc0346c6b86d401879ffb44058f7",
  json = "001c28d7a29832b06b0e831ec77845553c89b56d",
  yaml = "4463985dfccc640f3d6991e3396a2047610cf5f8",
  toml = "64b56832c2cffe41758f28e05c756a3a98d16f41",
  html = "73a3947324f6efddf9e17c0ea58d454843590cc0",
  css = "dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f",
  regex = "b2ac15e27fce703d2f37a79ccd94a5c0cbe9720b",
  diff = "2520c3f934b3179bb540d23e0ef45f75304b5fed",
  git_config = "0fbc9f99d5a28865f9de8427fb0672d66f9d83a5",
  graphql = "5e66e961eee421786bdda8495ed1db045e06b5fe",
  hcl = "64ad62785d442eb4d45df3a1764962dafd5bc98b",
  terraform = "64ad62785d442eb4d45df3a1764962dafd5bc98b",
}
